Lab 3
ilKogan/oaip pull request #1
Opened 2019-11-03 12:15 UTC by ilKogan

2019-11-04 08:20 UTC, kleap requested changes
Please pay attention to comments

2019-11-04 08:20 UTC, kleap commented on Lab3/Lab3/Lab3.cpp
> +#include <string>
Why do you need "string", don't you use char arrays?

2019-11-04 08:20 UTC, kleap commented on Lab3/Lab3/Lab3.cpp
> +		printf("Task 2");
If you need to put line break, you could try that approach https://stackoverflow.com/questions/10693431/how-do-i-add-a-newline-using-printf 
So it will be atomic operation to print message

2019-11-04 08:20 UTC, kleap commented on Lab3/Lab3/Lab3.cpp
> +namespace lab3
It might be better to name lab03, because it will look more consistent with everything else for example you will have lab10 ,😊

2019-11-04 08:20 UTC, kleap commented on Lab3/Lab3/Lab3.cpp
> +	void lab3_5()
In general this should be written in another way. Your `lab3_*` functions should contain only calculation logic and return value. So all printing and formatting should be in the `main`

2019-11-04 09:37 UTC, kleap commented on Lab3/Lab3/Lab3.cpp
> +#include <string>
Please clean up modules dependencies

2019-11-04 12:16 UTC, kleap commented
@ilKogan, please change the language in prints and logs to English

2019-11-04 12:22 UTC, kleap commented
And please choose only one lib for input/output from console, currently you use `iostream` and `conio.h`. It's better to use one approach.

2019-11-04 12:22 UTC, kleap commented
Please delete `iomanip` from headers. It's not used anywhere

2019-11-04 12:26 UTC, kleap commented
In your case the best choice to wait for user reaction to continue program execution is `system("pause")` from `iostream`. This method will also print `Press any key to continue . . .` on the screen.

2019-11-11 13:54 UTC, kleap commented on lab03/lab03.cpp
> +		tsk3_k = 4,
It would be better to use preprocessor directive for constant variables  `#define TASK_3_X 5e-5`

2019-11-11 13:56 UTC, kleap commented on lab03/lab03.cpp
> +		tsk3_k = 4,
[Take a look at it here](https://ru.wikibooks.org/wiki/%D0%A1%D0%B8%2B%2B/%D0%9F%D1%80%D0%B5%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%BD%D1%8B%D0%B5_%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D1%8B#%D0%94%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%B0_define)

2019-11-11 13:58 UTC, kleap requested changes
In general it looks good to me, but please make requested changes to constants

2019-11-11 14:05 UTC, kleap commented
Use directives only for meaningful constants, don't use it for "print" strings

2020-01-30 11:01 UTC, ArtemySinitsa commented on lab03/lab03.cpp
> +
```suggestion

```

2020-01-30 11:02 UTC, ArtemySinitsa submitted a review, later dismissed

2020-01-30 11:03 UTC, kleap submitted a review, later dismissed

2020-01-30 11:09 UTC, kleap approved these changes

2020-01-30 11:09 UTC, merged